### ISSUE TITLE
Not automatically Watch App  install with Mobile App

### ISSUE THREAD

**Issue by umeshbsa** [amoledwatchfaces/Complications-Suite-Wear-OS#11]
I have an issue.

I have created two application
1. Mobile
2. Watch

I uploaded both bundles to the play store
1. Mobile as the Normal way to publish
2. Watch- used key factor in Advance Setting

My problem is when I install a Mobile app on the phone. watch app is not installed automatically on the watch.

I follow this repo. please apply me what I am missing.

**Comment by amoledwatchfaces** [comment]
Hello, it's not possible to remotely install Wear OSs app this way. It needs to be installed manually by user directly in the Play Store.

**Comment by umeshbsa** [comment]
But I checked in your app. It's possible. 

This is your app.
![123](https://github.com/amoledwatchfaces/Complications-Suite-Wear-OS/assets/8288534/e378b23a-cbdc-4a3f-9e4e-3efee3bd88c7)


this is my app.
![ww](https://github.com/amoledwatchfaces/Complications-Suite-Wear-OS/assets/8288534/6a6720fb-5044-4f04-828a-d02ff5383ad3)


What I am missing in a watch or mobile manifest config or play store config.
please help me asap.
