### ISSUE TITLE
play store is not showing more device option.

### ISSUE THREAD

**Issue by umeshbsa** [amoledwatchfaces/Complications-Suite-Wear-OS#12]
I have two Mobile and watch applications and both are published on the play store.

I checked your app. It's showing more device options.
Please check the screenshots. 
![123](https://github.com/amoledwatchfaces/Complications-Suite-Wear-OS/assets/8288534/50212b74-2079-4950-9998-e0f42abc51fc)

But When I open my app on the play store, it's not showing more option
Please check the screenshots. 
![ww](https://github.com/amoledwatchfaces/Complications-Suite-Wear-OS/assets/8288534/3b1223d3-5838-4fdb-92d3-7816e241f10d)

What I am missing in manifest config in both Mobile and watch. or missing on the play store setup.
please help me.

**Comment by amoledwatchfaces** [comment]
Hi. If you have mobile app in mobile phone track and wear os app in wear os track, then installation button will appear in a few days, maybe a week. It depends on Google. Install button isn't available automatically.

**Comment by umeshbsa** [comment]
Just like your screenshot??
