### ISSUE TITLE
BTC/ETH price complications not updating anymore

### ISSUE THREAD

**Issue by BashMellow** [amoledwatchfaces/Complications-Suite-Wear-OS#14]
Hi, Binance delisted BTCBUSD and ETHBUSD pairs, so the complications do not update anymore. Could you please fix them, for instance by replacing the pairs with their USDT counterparts?

Thank you for your awesome work!

**Comment by amoledwatchfaces** [comment]
Hi. Absolutely! I'll try to fix this asap.

Thanks for letting me know 🙂

**Comment by amoledwatchfaces** [comment]
Fixed with 
https://github.com/amoledwatchfaces/Complications-Suite-Wear-OS/releases/tag/v2.9.2
