### ISSUE TITLE
BTC Complication stopped working

### ISSUE THREAD

**Issue by gitlaman** [amoledwatchfaces/Complications-Suite-Wear-OS#15]
As the title says, the BTC price ticker stopped working around week ago when the price was 42.8k. I reinstalled the app on my watch but now it does not show anything when i add btc complication.

Thanks

**Comment by gitlaman** [comment]
It wasnt working on samsung 6 classic watch face , purchased one of your watch faces and is working on them

**Comment by gitlaman** [comment]
Again is not updating on your watch faces, it was working for a while and now it is not updating at all

**Comment by amoledwatchfaces** [comment]
BTC price is not moving much these days. Compilation is definitely working in the latest version.
