### ISSUE TITLE
[SUGGESTION] Kaomoji Complication 

### ISSUE THREAD

**Issue by kushal-03** [amoledwatchfaces/Complications-Suite-Wear-OS#16]
It would be great if there was a kaomoji complication. Something like how I have attached in the picture. and would change periodically. 
![Screenshot_20240114_151904_weather](https://github.com/amoledwatchfaces/Complications-Suite-Wear-OS/assets/147609480/22bfdfcf-fb4e-4449-8ba9-b024fcb95c4a)

**Comment by amoledwatchfaces** [comment]
Hi, I think you can achieve a similar effect by using a custom text complication, set text to whatever text-emoji you like and set the title to an empty string.

**Comment by kushal-03** [comment]
Yes, I do agree with that. But it would be great if it could change according to the stress levels (even heart rate) or a certain time period.

**Comment by amoledwatchfaces** [comment]
That's something more suited for Health Plugin app. I'll see what can I do.

**Comment by kushal-03** [comment]
Thanks :))
