### ISSUE TITLE
Suggestion: Set default currency in settings / Expand ticker currencies

### ISSUE THREAD

**Issue by chadsr** [amoledwatchfaces/Complications-Suite-Wear-OS#18]
Hi, thanks for your work on this!

Since you have introduced cryptocurrency tickers, it would be nice to see a setting to control the default currency on a global setting. This way, maybe instead of choosing a particular crypto<->currency pair, they can just be switched automatically based on the global setting?

Alternatively if you're not keen on some global currency setting, it would at least be great to see some more currencies for the tickers! (EUR especially)

**Comment by Priyamshah72** [comment]
Would really love to have this feature, hope the developer are able to do it.

**Comment by amoledwatchfaces** [comment]
> Alternatively if you're not keen on some global currency setting, it would at least be great to see some more currencies for the tickers! (EUR especially)

@chadsr @Priyamshah72 

EUR Counter Currency will be added in the next release. (Toggle in the settings). So far there is no single API which would serve good for this project. CoinGecko is limited to 10000 calls / mo. This app uses Coinbase products and it only covers properly EUR, USD. 

https://github.com/amoledwatchfaces/Complications-Suite-Wear-OS/commit/a935ef6d8b23c1b77bb5e53f997141f2ff6b8499
