### ISSUE TITLE
Hi-Lo temperature

### ISSUE THREAD

**Issue by mananong** [amoledwatchfaces/Complications-Suite-Wear-OS#22]
Before updates in the weather complications apk, the hi-lo temp complication showed High, Low and Current temp. Last update changed the Current temp to a weather condition icon, please revert it back to showing the current temp in celcius/farenheit. Also the chance of rain always show high percentage of rain but every other weather source and actual real world weather is sunny or 0% chance, please fix

**Comment by amoledwatchfaces** [comment]
Not Complications Suite related. 
Please use support@amoledwatchfaces.com
