### ISSUE TITLE
$ADA complication only says 0

### ISSUE THREAD

**Issue by ZeZekeZ** [amoledwatchfaces/Complications-Suite-Wear-OS#26]
I've been using this complication set for a long time but recently got the idea to display the price of my Crypto of choice, Cardano. However, once I selected it, the complication only reports 0, which isn't correct. I looked around and I can't find any settings for it, is there a way to fix it?

**Comment by amoledwatchfaces** [comment]
Hi. Complications Suite only provides BTC and ETH tickers. I'm not sure where you found the ADA but it was certainly not in this app. Multiple crypto complications are not planned. Crypto APIs are paid and free ones are not suitable. Maybe you can try other apps?

**Comment by ZeZekeZ** [comment]
Thanks for getting back to me. Unfortunately, there doesn't seem to be any
other apps that support Cardano.
